backend:
  name: github
  repo: sayinokan/docs
  branch: main
  use_graphql: true
  client_id: Ov23li39sr3jN9DkIR1J

site_url: https://oduyoapi.netlify.app
display_url: https://oduyoapi.netlify.app

media_folder: "docs/assets/uploads"
public_folder: "/assets/uploads"

publish_mode: editorial_workflow

collections:
  - name: "docs"
    label: "Dokümantasyon"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Başlık", name: "title", widget: "string" }
      - { label: "İçerik", name: "body", widget: "markdown" }






