backend:
  name: github
  repo: sayinokan/oduyo-api
  branch: main

media_folder: "docs/assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "docs"
    label: "Dok√ºmanlar"
    folder: "docs"
    create: true
    nested:
      depth: 3
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }





